// <auto-generated />
using DotNet_Gram.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNet_Gram.Migrations
{
    [DbContext(typeof(NetGramDbContext))]
    [Migration("20190213194932_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNet_Gram.Models.NetGram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption");

                    b.Property<string>("ImageURL");

                    b.Property<string>("NamePoster");

                    b.HasKey("ID");

                    b.ToTable("NetGrams");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Caption = "pic",
                            ImageURL = "url",
                            NamePoster = "Jason"
                        },
                        new
                        {
                            ID = 2,
                            Caption = "pic",
                            ImageURL = "URL",
                            NamePoster = "Jennifer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
